<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9010a0d736572766963652e70726f746f120a79676f73657276696365" .
            "22790a0752657175657374120e0a066d6574686f64180120012809122f0a" .
            "06706172616d7318022003280b321f2e79676f736572766963652e526571" .
            "756573742e506172616d73456e7472791a2d0a0b506172616d73456e7472" .
            "79120b0a036b6579180120012809120d0a0576616c75651802200128093a" .
            "02380122190a055265706c7912100a08726573706f6e7365180120012809" .
            "323e0a0a59474f5365727669636512300a0443616c6c12132e79676f7365" .
            "72766963652e526571756573741a112e79676f736572766963652e526570" .
            "6c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

